export const siteConfig = {
  name: "lcdamy | Developer Portfolio",
  authorName: "lcdamy",
  username: "lcdamy",
  description:
    "lcdamy's portfolio - A software engineer with 10 years of experience in web development, specializing in building scalable and efficient applications. Passionate about coding, problem-solving, and continuous learning.",
  url: "https://lcdamy.netlify.app",
  links: {
    twitter: "https://x.com/lcdamy",
    github: "https://github.com/lcdamy",
  },
  ogImage: "https://lcdamy.netlify.app/peter-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "lcdamy",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
